INSTALL
- FAISS - 
- Sent2Vec

In [1]:
import numpy as np
import faiss   

In [2]:
import os
import time
name = "Buddhism-sent2vec-en-vi-0.999-"+ str(time.strftime("%Y%m%d-%H%M"))

!mkdir $name
path = os.getcwd() + "/" + name
os.chdir(path)

!pwd


os.chdir(path)

/home/chinh/clc_data/Script/Buddhism-sent2vec-en-vi-0.999-20210408-1742


In [3]:
!wget https://github.com/hoangtrungchinh/clc_data/raw/master/buddhism.tar.gz
!mkdir data_bin
!tar -xvf  'buddhism.tar.gz' -C 'data_bin'

--2021-04-08 17:42:30--  https://github.com/hoangtrungchinh/clc_data/raw/master/buddhism.tar.gz
Resolving github.com (github.com)... 192.30.255.113
Connecting to github.com (github.com)|192.30.255.113|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/hoangtrungchinh/clc_data/master/buddhism.tar.gz [following]
--2021-04-08 17:42:32--  https://raw.githubusercontent.com/hoangtrungchinh/clc_data/master/buddhism.tar.gz
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.111.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 910043 (889K) [application/octet-stream]
Saving to: ‘buddhism.tar.gz’

buddhism.tar.gz     100%[===================>] 888,71K  3,38MB/s    in 0,3s    

2021-04-08 17:42:32 (3,38 MB/s) - ‘buddhism.tar.gz’ saved [910043/910043]

Buddhism.vi


In [4]:
# import file
import numpy as np
import glob

en_files = sorted(glob.glob("data_bin/*.en"))
vi_files = sorted(glob.glob("data_bin/*.vi"))
print(en_files)
print(vi_files)

lst_en = []
lst_vi = []

start = time.time()

for file in en_files:
  with open(file) as file_in:
    for line in file_in:
      lst_en.append(line)

for file in vi_files:
  with open(file) as file_in:
    for line in file_in:
      lst_vi.append(line)

print(len(lst_en))
print(len(lst_vi))

['data_bin/Buddhism.en']
['data_bin/Buddhism.vi']
12880
12880


In [5]:
# SPLIT TRAIN, TEST, VALID
from sklearn.model_selection import train_test_split
en_train, en_test_valid, vi_train, vi_test_valid =  train_test_split(lst_en, lst_vi, test_size=0.2, random_state=123)
en_valid, en_test, vi_valid, vi_test = train_test_split(en_test_valid, vi_test_valid, test_size=0.5, random_state=123)
print(len(en_train))
print(len(vi_train))
print(len(en_valid))
print(len(vi_valid))
print(len(en_test))
print(len(vi_test))
print(en_train[20])
print(vi_train[20])
print(en_valid[-1])
print(vi_valid[-1])
print(en_test[-1])
print(vi_test[-1])

10304
10304
1288
1288
1288
1288
Every day after lunch, I helped the two temple boys clean the kitchen, then I left for a two-mile walk to a temple in the next village, where the head monk would drill me in Pali lessons.

Mỗi ngày sau bữa ăn, tôi phụ hai cậu bé ở chùa dọn dẹp nhà bếp, rồi tôi phải đi bộ gần ba cây số để đến một ngôi chùa ở làng kế bên, nơi vị trụ trì ở đó sẽ dạy tiếng Pali cho tôi.

If we are earnest, we should understand this problem of experience.

Nếu chúng ta nghiêm túc, chúng ta nên hiểu rõ vấn đề của trải nghiệm này.

You may be very generous in giving a large donation to your society, to your friends, but awfully mean about giving a bigger tip—you know what I mean by ‘mean’.

Bạn có lẽ rất quảng đại khi trao một hiến dâng to tát cho xã hội của bạn, cho bạn bè của bạn, nhưng rất keo kiệt khi cho một món quà lớn hơn – bạn biết tôi có ý gì qua từ ngữ ‘keo kiệt’.



In [6]:
file_variable = [en_train,vi_train,en_valid,vi_valid,en_test,vi_test]
file_names = ["en_train","vi_train","en_valid","vi_valid","en_test","vi_test"]

for i in range(len(file_names)):
  with open(file_names[i], 'w') as f:
    for item in file_variable[i]:
      f.write(item)
!ls -al

total 3972
drwxrwxr-x  3 chinh chinh    4096 Thg 4   8 17:42 .
drwxrwxr-x 16 chinh chinh    4096 Thg 4   8 17:42 ..
-rw-rw-r--  1 chinh chinh  910043 Thg 4   8 17:42 buddhism.tar.gz
drwxrwxr-x  2 chinh chinh    4096 Thg 4   8 17:42 data_bin
-rw-rw-r--  1 chinh chinh  127163 Thg 4   8 17:42 en_test
-rw-rw-r--  1 chinh chinh 1023485 Thg 4   8 17:42 en_train
-rw-rw-r--  1 chinh chinh  125859 Thg 4   8 17:42 en_valid
-rw-rw-r--  1 chinh chinh  182237 Thg 4   8 17:42 vi_test
-rw-rw-r--  1 chinh chinh 1486401 Thg 4   8 17:42 vi_train
-rw-rw-r--  1 chinh chinh  184873 Thg 4   8 17:42 vi_valid


In [7]:
start = time.time()
import sent2vec
model = sent2vec.Sent2vecModel()
model.load_model('../../../wiki_unigrams.bin')

print('=== Ending, Total time (second): ', time.time() - start)

=== Ending, Total time (second):  9.072224140167236


In [8]:
srcfile = "en_train"
tarfile = "vi_train"
# lst_srcfile = open(srcfile, "r").readlines()
# lst_tarfile = open(tarfile, "r").readlines()
lst_srcfile = en_train
lst_tarfile = vi_train

vec_lst_srcfile = model.embed_sentences(lst_srcfile)

Test Cosin similarity

In [9]:
import faiss

start = time.time()
vec_lst_srcfile = model.embed_sentences(lst_srcfile)
index = faiss.IndexFlatL2(600)
index.ntotal
faiss.normalize_L2(vec_lst_srcfile)
index.add(vec_lst_srcfile)
k = 6
distance, index = index.search(vec_lst_srcfile, k)

print('=== Ending, Total time (second): ', time.time() - start)
print(len(distance))
print(len(index))

print(index)
print(distance)

=== Ending, Total time (second):  0.33879971504211426
10304
10304
[[    0  5715  1742   597  9241  5380]
 [    1  3520  4428  3897  3763  9449]
 [    2  9928  9070  3498  6860   503]
 ...
 [10301 10069  6259  1807  7503  3555]
 [10302  9194  6782   956  9429  4538]
 [10303   329   478   100  1208  1028]]
[[4.7683716e-07 7.6361585e-01 7.6419914e-01 8.3771658e-01 8.5858643e-01
  8.7362075e-01]
 [4.7683716e-07 6.5204394e-01 7.4527025e-01 7.5698471e-01 7.9065466e-01
  7.9523373e-01]
 [0.0000000e+00 7.5219345e-01 7.7750969e-01 8.3772433e-01 8.4872437e-01
  8.5395491e-01]
 ...
 [0.0000000e+00 6.5340424e-01 8.0812383e-01 8.2349205e-01 8.2415068e-01
  8.2527947e-01]
 [0.0000000e+00 6.3898289e-01 7.9943395e-01 8.4639382e-01 8.6467588e-01
  8.8177025e-01]
 [0.0000000e+00 1.0000002e+00 1.0000002e+00 1.0000002e+00 1.0000002e+00
  1.0000002e+00]]


In [10]:
print(type(vec_lst_srcfile))
print(vec_lst_srcfile.shape)


<class 'numpy.ndarray'>
(10304, 600)


In [11]:
i = 6
j = k-1
print(index[i][j])
print("==================================")
print(distance[i][j])
a = vec_lst_srcfile[i]
# print(a)
b = vec_lst_srcfile[index[i][j]]
# TEST
dist_squared = np.sum(np.square(a - b))
print(dist_squared)

329
0.9999999
0.99999994


In [12]:
start = time.time()
saperate = " || "

src_label = "S"
emb_label = "E"
thres_arr = [0.8, 0.85, 0.9, 0.95, 0.99]
for i in range(len(thres_arr)):
    threshold = thres_arr[i]
    out_file_write = open("en_train_EM_"+str(thres_arr[i]), 'w')
    out_file_write_score = open("en_train_EM_score_"+str(thres_arr[i]), 'w')
    out_file_write_factor = open("en_train_EM_factor_"+str(thres_arr[i]), 'w')
    num_gth_thres = 0

    for i in range(len(lst_srcfile)):
        score = distance[i][1]
        content = ""
        content_label_arr = []
        if score >= threshold:
            num_gth_thres += 1
            best_simi_index = index[i][1]
            content = lst_srcfile[i].strip() + saperate + lst_tarfile[best_simi_index].strip()

            content_label = [src_label] * len(lst_srcfile[i].split())
            content_label.append(emb_label)
            content_label = content_label + [emb_label] * len(lst_tarfile[best_simi_index].split())

            content_label_arr = " ".join(content_label)
        else:
            content = lst_srcfile[i].strip()
            content_label = [src_label] * len(lst_srcfile[i].split())
            content_label_arr = " ".join(content_label)
 
        out_file_write.writelines(content+ "\n")    
        out_file_write_factor.writelines(content_label_arr + "\n")
        out_file_write_score.writelines(str(score) + "\n")

    print('threshold =', threshold, "EM sentences =", num_gth_thres, "/", len(lst_srcfile), num_gth_thres/len(lst_srcfile), "%" )

    out_file_write.close()
    out_file_write_score.close()
    out_file_write_factor.close()

done = time.time()
elapsed = done - start
print('=== Ending, Total time (second): ', elapsed)

threshold = 0.8 EM sentences = 6885 / 10304 0.6681871118012422 %
threshold = 0.85 EM sentences = 6027 / 10304 0.5849184782608695 %
threshold = 0.9 EM sentences = 5072 / 10304 0.4922360248447205 %
threshold = 0.95 EM sentences = 4049 / 10304 0.39295419254658387 %
threshold = 0.99 EM sentences = 3246 / 10304 0.31502329192546585 %
=== Ending, Total time (second):  0.8569827079772949
