INSTALL
- FAISS - 
- Sent2Vec

In [1]:
import numpy as np
import faiss   

In [2]:
import os
import time
name = "Faiss-EM-TED-distilroberta-vi-en"+ str(time.strftime("%Y%m%d-%H%M"))

!mkdir $name
path = os.getcwd() + "/" + name
os.chdir(path)

!pwd


os.chdir(path)


# import os
# os.chdir("/home/lw/clc_fairseq/TED-20210121-1335")

/home/chinh/clc_data/Script/Faiss-EM-TED-Bert-vi-en20210227-1156


In [3]:
!wget https://github.com/hoangtrungchinh/clc_data/raw/master/en_vi_iwslt.tar.gz
!mkdir data_bin
!tar -xvf  'en_vi_iwslt.tar.gz' -C 'data_bin'

--2021-02-27 11:56:18--  https://github.com/hoangtrungchinh/clc_data/raw/master/en_vi_iwslt.tar.gz
Resolving github.com (github.com)... 52.74.223.119
Connecting to github.com (github.com)|52.74.223.119|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/hoangtrungchinh/clc_data/master/en_vi_iwslt.tar.gz [following]
--2021-02-27 11:56:19--  https://raw.githubusercontent.com/hoangtrungchinh/clc_data/master/en_vi_iwslt.tar.gz
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.108.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 9044100 (8,6M) [application/octet-stream]
Saving to: ‘en_vi_iwslt.tar.gz’

en_vi_iwslt.tar.gz  100%[===================>]   8,62M  7,11MB/s    in 1,2s    

2021-02-27 11:56:21 (7,11 MB/s) - ‘en_vi_iwslt.tar.gz’ saved [9044100/904410

In [4]:
# import file
import numpy as np
import glob

en_files = sorted(glob.glob("data_bin/*.en"))
vi_files = sorted(glob.glob("data_bin/*.vi"))
print(en_files)
print(vi_files)

lst_en = []
lst_vi = []

start = time.time()

for file in en_files:
  with open(file) as file_in:
    for line in file_in:
      lst_en.append(line)

for file in vi_files:
  with open(file) as file_in:
    for line in file_in:
      lst_vi.append(line)

print(len(lst_en))
print(len(lst_vi))

['data_bin/IWSLT15.TED.tst2012.en-vi.en', 'data_bin/IWSLT15.TED.tst2013.en-vi.en', 'data_bin/IWSLT15.TED.tst2015.en-vi.en', 'data_bin/train.en']
['data_bin/IWSLT15.TED.tst2012.en-vi.vi', 'data_bin/IWSLT15.TED.tst2013.en-vi.vi', 'data_bin/IWSLT15.TED.tst2015.en-vi.vi', 'data_bin/train.vi']
120956
120956


In [5]:
# SPLIT TRAIN, TEST, VALID
from sklearn.model_selection import train_test_split
en_train, en_test_valid, vi_train, vi_test_valid =  train_test_split(lst_en, lst_vi, test_size=0.2, random_state=123)
en_valid, en_test, vi_valid, vi_test = train_test_split(en_test_valid, vi_test_valid, test_size=0.5, random_state=123)
print(len(en_train))
print(len(vi_train))
print(len(en_valid))
print(len(vi_valid))
print(len(en_test))
print(len(vi_test))
print(en_train[20])
print(vi_train[20])
print(en_valid[-1])
print(vi_valid[-1])
print(en_test[-1])
print(vi_test[-1])

96764
96764
12096
12096
12096
12096
And , in fact , when we did some experiments looking at this , what we found is that 46 percent of the variation in how many friends you have is explained by your genes .

Trong thực tế , khi thực hiện một vài thí nghiệm nghiên cứu vấn đề này , chúng tôi nhận ra 46 % sự khác biệt trong số bạn bè của bạn được giải thích bằng gen của bạn .

This is a chart of what it looked like when it first became popular last summer .

Đây là biểu đồ thể hiện điều đó khi video này lần đầu tiên trở nên phổ biến vào mùa hè trước .

And what will happen in the future ?

Chuyện gì sẽ xảy ra trong tương lai ?



In [6]:
file_variable = [en_train,vi_train,en_valid,vi_valid,en_test,vi_test]
file_names = ["en_train","vi_train","en_valid","vi_valid","en_test","vi_test"]

for i in range(len(file_names)):
  with open(file_names[i], 'w') as f:
    for item in file_variable[i]:
      f.write(item)
!ls -al

total 36844
drwxrwxr-x 3 chinh chinh     4096 Thg 2  27 11:56 .
drwxrwxr-x 6 chinh chinh     4096 Thg 2  27 11:56 ..
drwxrwxr-x 2 chinh chinh     4096 Thg 2  27 11:56 data_bin
-rw-rw-r-- 1 chinh chinh  1260181 Thg 2  27 11:56 en_test
-rw-rw-r-- 1 chinh chinh 10011509 Thg 2  27 11:56 en_train
-rw-rw-r-- 1 chinh chinh  1249342 Thg 2  27 11:56 en_valid
-rw-rw-r-- 1 chinh chinh  9044100 Thg 2  27 11:56 en_vi_iwslt.tar.gz
-rw-rw-r-- 1 chinh chinh  1624771 Thg 2  27 11:56 vi_test
-rw-rw-r-- 1 chinh chinh 12896000 Thg 2  27 11:56 vi_train
-rw-rw-r-- 1 chinh chinh  1609835 Thg 2  27 11:56 vi_valid


In [7]:
from sentence_transformers import SentenceTransformer, util
model = SentenceTransformer('paraphrase-distilroberta-base-v1')
# # model = SentenceTransformer('LaBSE')
# #Sentences are encoded by calling model.encode()
# emb1 = model.encode("This is a red cat with a hat.")
# emb2 = model.encode("Have you seen my red cat?")

# cos_sim = util.pytorch_cos_sim(emb1, emb2)
# print("Cosine-Similarity:", cos_sim)

In [8]:
start = time.time()
srcfile = "vi_train"
tarfile = "en_train"
# lst_srcfile = open(srcfile, "r").readlines()
# lst_tarfile = open(tarfile, "r").readlines()
lst_srcfile = vi_train
lst_tarfile = en_train

vec_lst_srcfile = model.encode(lst_srcfile)
print('=== Ending, Total time (second): ', time.time() - start)

=== Ending, Total time (second):  651.1811723709106


Test Cosin similarity

In [9]:
import faiss

start = time.time()
index = faiss.IndexFlatL2(768)
index.ntotal
faiss.normalize_L2(vec_lst_srcfile)
index.add(vec_lst_srcfile)
k = 6
distance, index = index.search(vec_lst_srcfile, k)

print('=== Ending, Total time (second): ', time.time() - start)
print(len(distance))
print(len(index))

print(index)
print(distance)

=== Ending, Total time (second):  38.3506076335907
96764
96764
[[    0 66198 93893  1847 70164 42122]
 [    1 45229 90252 38465 22043 66924]
 [    2 68289 38801 78954  6667 43814]
 ...
 [96761 90346 75368 44970 31659 52293]
 [96762 86987  4286 67620 70190 22749]
 [96763 10916  7886 69274 34687 45315]]
[[0.0000000e+00 1.6968155e-01 1.7118824e-01 1.7121243e-01 1.7494512e-01
  1.7620480e-01]
 [0.0000000e+00 1.6705418e-01 1.8024969e-01 1.8405783e-01 1.8882930e-01
  1.9314837e-01]
 [0.0000000e+00 2.3591542e-01 2.4088609e-01 2.5170004e-01 2.5979006e-01
  2.5999165e-01]
 ...
 [0.0000000e+00 2.3677850e-01 2.4555230e-01 2.6640487e-01 2.6938546e-01
  2.7425909e-01]
 [1.1920929e-07 1.8696308e-01 1.9252396e-01 1.9541562e-01 2.0005262e-01
  2.1628165e-01]
 [2.3841858e-07 2.4108267e-01 2.5434709e-01 2.5683343e-01 2.5808859e-01
  2.5925899e-01]]


In [10]:
i = 6
j = k-1
print(index[i][j])
print("==================================")
print(distance[i][j])
a = vec_lst_srcfile[i]
# print(a)
b = vec_lst_srcfile[index[i][j]]
# TEST
dist_squared = np.sum(np.square(a - b))
print(dist_squared)

19607
0.16375113
0.16375084


In [11]:
start = time.time()
saperate = " || "

src_label = "S"
emb_label = "E"
thres_arr = [0.9, 0.8, 0.7, 0.6]
for i in range(len(thres_arr)):
    threshold = thres_arr[i]
    out_file_write = open("vi_train_EM_"+str(thres_arr[i]), 'w')
    out_file_write_score = open("vi_train_EM_score_"+str(thres_arr[i]), 'w')
    out_file_write_factor = open("vi_train_EM_factor_"+str(thres_arr[i]), 'w')
    num_gth_thres = 0

    for i in range(len(lst_srcfile)):
        score = distance[i][1]
        content = ""
        content_label_arr = []
        if score >= threshold:
            num_gth_thres += 1
            best_simi_index = index[i][1]
            content = lst_srcfile[i].strip() + saperate + lst_tarfile[best_simi_index].strip()

            content_label = [src_label] * len(lst_srcfile[i].split())
            content_label.append(emb_label)
            content_label = content_label + [emb_label] * len(lst_tarfile[best_simi_index].split())

            content_label_arr = " ".join(content_label)
        else:
            content = lst_srcfile[i].strip()
            content_label = [src_label] * len(lst_srcfile[i].split())
            content_label_arr = " ".join(content_label)
 
        out_file_write.writelines(content+ "\n")    
        out_file_write_factor.writelines(content_label_arr + "\n")
        out_file_write_score.writelines(str(score) + "\n")

    print('threshold =', threshold, "EM sentences =", num_gth_thres, "/", len(lst_srcfile), num_gth_thres/len(lst_srcfile), "%" )

    out_file_write.close()
    out_file_write_score.close()
    out_file_write_factor.close()

done = time.time()
elapsed = done - start
print('=== Ending, Total time (second): ', elapsed)

threshold = 0.9 EM sentences = 101 / 96764 0.001043776611136373 %
threshold = 0.8 EM sentences = 253 / 96764 0.002614608738787152 %
threshold = 0.7 EM sentences = 612 / 96764 0.006324666198172874 %
threshold = 0.6 EM sentences = 1473 / 96764 0.015222603447563144 %
=== Ending, Total time (second):  7.912481307983398
