INSTALL
- FAISS - 
- Sent2Vec

In [1]:
import numpy as np
import faiss   

In [2]:
import os
import time
name = "Faiss-EM-TED-en-vi-500-1000-"+ str(time.strftime("%Y%m%d-%H%M"))

!mkdir $name
path = os.getcwd() + "/" + name
os.chdir(path)

!pwd


os.chdir(path)

/home/chinh/clc_data/Script/Faiss-EM-TED-en-vi-500-1000-20210311-1258


In [3]:
!wget https://github.com/hoangtrungchinh/clc_data/raw/master/en_vi_iwslt.tar.gz
!mkdir data_bin
!tar -xvf  'en_vi_iwslt.tar.gz' -C 'data_bin'

--2021-03-11 12:58:14--  https://github.com/hoangtrungchinh/clc_data/raw/master/en_vi_iwslt.tar.gz
Resolving github.com (github.com)... 13.250.177.223
Connecting to github.com (github.com)|13.250.177.223|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/hoangtrungchinh/clc_data/master/en_vi_iwslt.tar.gz [following]
--2021-03-11 12:58:15--  https://raw.githubusercontent.com/hoangtrungchinh/clc_data/master/en_vi_iwslt.tar.gz
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.110.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 9044100 (8,6M) [application/octet-stream]
Saving to: ‘en_vi_iwslt.tar.gz’

en_vi_iwslt.tar.gz  100%[===================>]   8,62M  9,89MB/s    in 0,9s    

2021-03-11 12:58:17 (9,89 MB/s) - ‘en_vi_iwslt.tar.gz’ saved [9044100/9044

In [4]:
# import file
import numpy as np
import glob

en_files = sorted(glob.glob("data_bin/*.en"))
vi_files = sorted(glob.glob("data_bin/*.vi"))
print(en_files)
print(vi_files)

lst_en = []
lst_vi = []

start = time.time()

for file in en_files:
  with open(file) as file_in:
    for line in file_in:
      lst_en.append(line)

for file in vi_files:
  with open(file) as file_in:
    for line in file_in:
      lst_vi.append(line)

print(len(lst_en))
print(len(lst_vi))

['data_bin/IWSLT15.TED.tst2012.en-vi.en', 'data_bin/IWSLT15.TED.tst2013.en-vi.en', 'data_bin/IWSLT15.TED.tst2015.en-vi.en', 'data_bin/train.en']
['data_bin/IWSLT15.TED.tst2012.en-vi.vi', 'data_bin/IWSLT15.TED.tst2013.en-vi.vi', 'data_bin/IWSLT15.TED.tst2015.en-vi.vi', 'data_bin/train.vi']
120956
120956


In [5]:
# SPLIT TRAIN, TEST, VALID
from sklearn.model_selection import train_test_split
en_train, en_test_valid, vi_train, vi_test_valid =  train_test_split(lst_en, lst_vi, test_size=0.01240120374, random_state=123)
en_valid, en_test, vi_valid, vi_test = train_test_split(en_test_valid, vi_test_valid, test_size=0.66666666, random_state=123)
print(len(en_train))
print(len(vi_train))
print(len(en_valid))
print(len(vi_valid))
print(len(en_test))
print(len(vi_test))
print(en_train[20])
print(vi_train[20])
print(en_valid[-1])
print(vi_valid[-1])
print(en_test[-1])
print(vi_test[-1])

119456
119456
500
500
1000
1000
And what I would like to maybe invite you to do by the end of this talk is explore where you are today , for two reasons . One : so that you can contribute more . And two : so that hopefully we can not just understand other people more , but maybe appreciate them more , and create the kinds of connections that can stop some of the challenges that we face in our society today .

Và tôi mong muốn là mời bạn tham gia một việc trước khi kết thúc buổi trò chuyện này , là khám phá ra bạn đang ở đâu ngày hôm nay , vì hai lý do . Một : bạn có thể cống hiến nhiều hơn . Và hai : hy vọng ta có thể không chỉ hiểu người khác nhiều hơn , mà có lẽ còn thấy biết ơn họ hơn , và tạo ra những mối liên kết có thể chặn trước vài vấn đề mà chúng ta đối mặt trong xã hội ngày nay .

So we have to wonder , if there is a multiverse , in some other patch of that multiverse , are there creatures ?

Thế nên ta phải tự hỏi , nếu có nhiều vũ trụ , và trong một vài phần của những ngân 

In [6]:
file_variable = [en_train,vi_train,en_valid,vi_valid,en_test,vi_test]
file_names = ["en_train","vi_train","en_valid","vi_valid","en_test","vi_test"]

for i in range(len(file_names)):
  with open(file_names[i], 'w') as f:
    for item in file_variable[i]:
      f.write(item)
!ls -al

total 36836
drwxrwxr-x 3 chinh chinh     4096 Thg 3  11 12:58 .
drwxrwxr-x 8 chinh chinh     4096 Thg 3  11 12:58 ..
drwxrwxr-x 2 chinh chinh     4096 Thg 3  11 12:58 data_bin
-rw-rw-r-- 1 chinh chinh   104840 Thg 3  11 12:58 en_test
-rw-rw-r-- 1 chinh chinh 12363629 Thg 3  11 12:58 en_train
-rw-rw-r-- 1 chinh chinh    52563 Thg 3  11 12:58 en_valid
-rw-rw-r-- 1 chinh chinh  9044100 Thg 3  11 12:58 en_vi_iwslt.tar.gz
-rw-rw-r-- 1 chinh chinh   135053 Thg 3  11 12:58 vi_test
-rw-rw-r-- 1 chinh chinh 15927506 Thg 3  11 12:58 vi_train
-rw-rw-r-- 1 chinh chinh    68047 Thg 3  11 12:58 vi_valid


In [7]:
start = time.time()
import sent2vec
model = sent2vec.Sent2vecModel()
model.load_model('../../../wiki_unigrams.bin')

print('=== Ending, Total time (second): ', time.time() - start)

=== Ending, Total time (second):  2.155622959136963


In [8]:
srcfile = "en_train"
tarfile = "vi_train"
# lst_srcfile = open(srcfile, "r").readlines()
# lst_tarfile = open(tarfile, "r").readlines()
lst_srcfile = en_train
lst_tarfile = vi_train

vec_lst_srcfile = model.embed_sentences(lst_srcfile)

Test Cosin similarity

In [9]:
import faiss

start = time.time()
vec_lst_srcfile = model.embed_sentences(lst_srcfile)
index = faiss.IndexFlatL2(600)
index.ntotal
faiss.normalize_L2(vec_lst_srcfile)
index.add(vec_lst_srcfile)
k = 6
distance, index = index.search(vec_lst_srcfile, k)

print('=== Ending, Total time (second): ', time.time() - start)
print(len(distance))
print(len(index))

print(index)
print(distance)

=== Ending, Total time (second):  44.32712650299072
119456
119456
[[     0  14098  79525  31597 116423  27382]
 [     1  64134  56895  37919  86341  25401]
 [     2  74792  59383  81100  57790  15709]
 ...
 [119453  13274  45821  19583  26967  94299]
 [119454  18673  24556   2007  99967  96871]
 [119455 108039  43876  66857  47297  14703]]
[[0.         0.49618948 0.49709058 0.4986843  0.54055536 0.54055536]
 [0.         0.42408764 0.4591887  0.499799   0.5023476  0.50570154]
 [0.         0.99267447 1.0280502  1.0287123  1.0339931  1.0354191 ]
 ...
 [0.         0.7048433  0.7905928  0.79185724 0.79934967 0.8122268 ]
 [0.         0.913921   0.9427881  1.0263987  1.03127    1.0327064 ]
 [0.         0.6701342  0.7692734  0.7846376  0.88304937 0.8837693 ]]


In [10]:
print(type(vec_lst_srcfile))
print(vec_lst_srcfile.shape)


<class 'numpy.ndarray'>
(119456, 600)


In [11]:
i = 6
j = k-1
print(index[i][j])
print("==================================")
print(distance[i][j])
a = vec_lst_srcfile[i]
# print(a)
b = vec_lst_srcfile[index[i][j]]
# TEST
dist_squared = np.sum(np.square(a - b))
print(dist_squared)

44810
0.386482
0.3864819


In [12]:
start = time.time()
saperate = " || "

src_label = "S"
emb_label = "E"
thres_arr = [0.9, 0.8, 0.7, 0.6]
for i in range(len(thres_arr)):
    threshold = thres_arr[i]
    out_file_write = open("en_train_EM_"+str(thres_arr[i]), 'w')
    out_file_write_score = open("en_train_EM_score_"+str(thres_arr[i]), 'w')
    out_file_write_factor = open("en_train_EM_factor_"+str(thres_arr[i]), 'w')
    num_gth_thres = 0

    for i in range(len(lst_srcfile)):
        score = distance[i][1]
        content = ""
        content_label_arr = []
        if score >= threshold:
            num_gth_thres += 1
            best_simi_index = index[i][1]
            content = lst_srcfile[i].strip() + saperate + lst_tarfile[best_simi_index].strip()

            content_label = [src_label] * len(lst_srcfile[i].split())
            content_label.append(emb_label)
            content_label = content_label + [emb_label] * len(lst_tarfile[best_simi_index].split())

            content_label_arr = " ".join(content_label)
        else:
            content = lst_srcfile[i].strip()
            content_label = [src_label] * len(lst_srcfile[i].split())
            content_label_arr = " ".join(content_label)
 
        out_file_write.writelines(content+ "\n")    
        out_file_write_factor.writelines(content_label_arr + "\n")
        out_file_write_score.writelines(str(score) + "\n")

    print('threshold =', threshold, "EM sentences =", num_gth_thres, "/", len(lst_srcfile), num_gth_thres/len(lst_srcfile), "%" )

    out_file_write.close()
    out_file_write_score.close()
    out_file_write_factor.close()

done = time.time()
elapsed = done - start
print('=== Ending, Total time (second): ', elapsed)

threshold = 0.9 EM sentences = 12913 / 119456 0.1080983793195821 %
threshold = 0.8 EM sentences = 31761 / 119456 0.2658803241360836 %
threshold = 0.7 EM sentences = 52975 / 119456 0.4434687248861505 %
threshold = 0.6 EM sentences = 71765 / 119456 0.6007651352799357 %
=== Ending, Total time (second):  9.497036218643188
