INSTALL
- FAISS - 
- Sent2Vec

In [1]:
import numpy as np
import faiss   

In [2]:
import os
import time
name = "Faiss-EM-NDT-bert-en-vi-0.999-"+ str(time.strftime("%Y%m%d-%H%M"))

!mkdir $name
path = os.getcwd() + "/" + name
os.chdir(path)

!pwd


os.chdir(path)


# import os
# os.chdir("/home/lw/clc_fairseq/TED-20210121-1335")

/home/chinh/clc_data/Script/Faiss-EM-NDT-bert-en-vi-0.999-20210402-1607


In [3]:
!wget https://github.com/hoangtrungchinh/clc_data/raw/master/nguyenductuan.tar.gz
!mkdir data_bin
!tar -xvf  'nguyenductuan.tar.gz' -C 'data_bin'

--2021-04-02 16:07:03--  https://github.com/hoangtrungchinh/clc_data/raw/master/nguyenductuan.tar.gz
Resolving github.com (github.com)... 52.74.223.119
Connecting to github.com (github.com)|52.74.223.119|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/hoangtrungchinh/clc_data/master/nguyenductuan.tar.gz [following]
--2021-04-02 16:07:04--  https://raw.githubusercontent.com/hoangtrungchinh/clc_data/master/nguyenductuan.tar.gz
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.110.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 13394580 (13M) [application/octet-stream]
Saving to: ‘nguyenductuan.tar.gz’

nguyenductuan.tar.g 100%[===================>]  12,77M  7,74MB/s    in 1,7s    

2021-04-02 16:07:06 (7,74 MB/s) - ‘nguyenductuan.tar.gz’ saved [1339

In [4]:
# import file
import numpy as np
import glob

en_files = sorted(glob.glob("data_bin/*.en"))
vi_files = sorted(glob.glob("data_bin/*.vi"))
print(en_files)
print(vi_files)

lst_en = []
lst_vi = []

start = time.time()

for file in en_files:
  with open(file) as file_in:
    for line in file_in:
      lst_en.append(line)

for file in vi_files:
  with open(file) as file_in:
    for line in file_in:
      lst_vi.append(line)

print(len(lst_en))
print(len(lst_vi))

['data_bin/1.en']
['data_bin/1.vi']
380643
380643


In [5]:
# SPLIT TRAIN, TEST, VALID
from sklearn.model_selection import train_test_split
en_train, en_test_valid, vi_train, vi_test_valid =  train_test_split(lst_en, lst_vi, test_size=0.2, random_state=123)
en_valid, en_test, vi_valid, vi_test = train_test_split(en_test_valid, vi_test_valid, test_size=0.5, random_state=123)
print(len(en_train))
print(len(vi_train))
print(len(en_valid))
print(len(vi_valid))
print(len(en_test))
print(len(vi_test))
print(en_train[20])
print(vi_train[20])
print(en_valid[-1])
print(vi_valid[-1])
print(en_test[-1])
print(vi_test[-1])

304514
304514
38064
38064
38065
38065
He's out sick for two days.

Nghỉ ốm hai ngày rồi.

Yeah, she 'sexiled' you or whatever, right?

Ừ, cô ấy ép em dâm đãng hay gì đó phải không?

You were treated like a sick person.

Anh đã được đối xử như một người bệnh.



In [6]:
file_variable = [en_train,vi_train,en_valid,vi_valid,en_test,vi_test]
file_names = ["en_train","vi_train","en_valid","vi_valid","en_test","vi_test"]

for i in range(len(file_names)):
  with open(file_names[i], 'w') as f:
    for item in file_variable[i]:
      f.write(item)
!ls -al

total 46760
drwxrwxr-x  3 chinh chinh     4096 Thg 4   2 16:07 .
drwxrwxr-x 11 chinh chinh     4096 Thg 4   2 16:07 ..
drwxrwxr-x  2 chinh chinh     4096 Thg 4   2 16:07 data_bin
-rw-rw-r--  1 chinh chinh  1478082 Thg 4   2 16:07 en_test
-rw-rw-r--  1 chinh chinh 11817828 Thg 4   2 16:07 en_train
-rw-rw-r--  1 chinh chinh  1475267 Thg 4   2 16:07 en_valid
-rw-rw-r--  1 chinh chinh 13394580 Thg 4   2 16:07 nguyenductuan.tar.gz
-rw-rw-r--  1 chinh chinh  1968735 Thg 4   2 16:07 vi_test
-rw-rw-r--  1 chinh chinh 15754152 Thg 4   2 16:07 vi_train
-rw-rw-r--  1 chinh chinh  1963918 Thg 4   2 16:07 vi_valid


In [7]:
from sentence_transformers import SentenceTransformer, util
model = SentenceTransformer('stsb-bert-large')
# # model = SentenceTransformer('LaBSE')
# #Sentences are encoded by calling model.encode()
# emb1 = model.encode("This is a red cat with a hat.")
# emb2 = model.encode("Have you seen my red cat?")

# cos_sim = util.pytorch_cos_sim(emb1, emb2)
# print("Cosine-Similarity:", cos_sim)

In [8]:
# print(cos_sim.numpy()[0][0])

In [9]:
start = time.time()
srcfile = "en_train"
tarfile = "vi_train"
# lst_srcfile = open(srcfile, "r").readlines()
# lst_tarfile = open(tarfile, "r").readlines()
lst_srcfile = en_train
lst_tarfile = vi_train

vec_lst_srcfile = model.encode(lst_srcfile)
print('=== Ending, Total time (second): ', time.time() - start)

=== Ending, Total time (second):  1839.3935627937317


Test Cosin similarity

In [10]:
import faiss
# print(vec_lst_srcfile.shape[1])
start = time.time()
index = faiss.IndexFlatL2(vec_lst_srcfile.shape[1])
index.ntotal
faiss.normalize_L2(vec_lst_srcfile)
index.add(vec_lst_srcfile)
k = 6
distance, index = index.search(vec_lst_srcfile, k)

print('=== Ending, Total time (second): ', time.time() - start)
print(len(distance))
print(len(index))

print(index)
print(distance)

=== Ending, Total time (second):  499.39041900634766
304514
304514
[[     0 171197  87709 280882 217664 171131]
 [     1  57310 292296  75844 131819 157372]
 [     2    866  26867 116090 244699  77922]
 ...
 [304511 190585  69923 190053 181708 283756]
 [304512 155584 271476 277073 280816  32471]
 [304513 147507 249537 235763 275394 278257]]
[[0.0000000e+00 3.1040883e-01 3.4955812e-01 3.7668610e-01 3.8552010e-01
  4.0213704e-01]
 [2.3841858e-07 9.4573152e-01 9.6817505e-01 9.7280025e-01 9.7517765e-01
  9.8701441e-01]
 [0.0000000e+00 6.7612147e-01 8.3577967e-01 8.9306748e-01 9.0530157e-01
  9.0685022e-01]
 ...
 [0.0000000e+00 1.6155887e-01 1.6896379e-01 1.7248940e-01 2.0367694e-01
  2.0367718e-01]
 [0.0000000e+00 7.1165085e-01 7.9599035e-01 8.4876978e-01 8.6626041e-01
  8.8183188e-01]
 [0.0000000e+00 6.7183733e-02 6.9432139e-02 6.9432259e-02 7.4913740e-02
  1.2175012e-01]]


In [11]:
i = 6
j = k-1
print(index[i][j])
print("==================================")
print(distance[i][j])
a = vec_lst_srcfile[i]
# print(a)
b = vec_lst_srcfile[index[i][j]]
# TEST
dist_squared = np.sum(np.square(a - b))
print(dist_squared)

147155
0.81918657
0.8191867


In [12]:
start = time.time()
saperate = " || "

src_label = "S"
emb_label = "E"
thres_arr = [0.95, 0.99, 0.995, 0.999]
for i in range(len(thres_arr)):
    threshold = thres_arr[i]
    out_file_write = open("en_train_EM_"+str(thres_arr[i]), 'w')
    out_file_write_score = open("en_train_EM_score_"+str(thres_arr[i]), 'w')
    out_file_write_factor = open("en_train_EM_factor_"+str(thres_arr[i]), 'w')
    num_gth_thres = 0

    for i in range(len(lst_srcfile)):
        score = distance[i][1]
        content = ""
        content_label_arr = []
        if score >= threshold:
            num_gth_thres += 1
            best_simi_index = index[i][1]
            content = lst_srcfile[i].strip() + saperate + lst_tarfile[best_simi_index].strip()

            content_label = [src_label] * len(lst_srcfile[i].split())
            content_label.append(emb_label)
            content_label = content_label + [emb_label] * len(lst_tarfile[best_simi_index].split())

            content_label_arr = " ".join(content_label)
        else:
            content = lst_srcfile[i].strip()
            content_label = [src_label] * len(lst_srcfile[i].split())
            content_label_arr = " ".join(content_label)
 
        out_file_write.writelines(content+ "\n")    
        out_file_write_factor.writelines(content_label_arr + "\n")
        out_file_write_score.writelines(str(score) + "\n")

    print('threshold =', threshold, "EM sentences =", num_gth_thres, "/", len(lst_srcfile), num_gth_thres/len(lst_srcfile), "%" )

    out_file_write.close()
    out_file_write_score.close()
    out_file_write_factor.close()

done = time.time()
elapsed = done - start
print('=== Ending, Total time (second): ', elapsed)

threshold = 0.95 EM sentences = 3514 / 304514 0.011539699324169003 %
threshold = 0.99 EM sentences = 1669 / 304514 0.005480864590790571 %
threshold = 0.995 EM sentences = 1496 / 304514 0.004912746211996821 %
threshold = 0.999 EM sentences = 1378 / 304514 0.0045252435027617775 %
=== Ending, Total time (second):  12.267041206359863
