INSTALL
- FAISS - 
- Sent2Vec

In [1]:
import numpy as np
import faiss   

In [2]:
import os
import time
name = "Faiss-EM-TED-bert-en-vi-500-1000-"+ str(time.strftime("%Y%m%d-%H%M"))

!mkdir $name
path = os.getcwd() + "/" + name
os.chdir(path)

!pwd


os.chdir(path)


# import os
# os.chdir("/home/lw/clc_fairseq/TED-20210121-1335")

/home/chinh/clc_data/Script/Faiss-EM-TED-bert-en-vi-500-1000-20210311-1226


In [3]:
!wget https://github.com/hoangtrungchinh/clc_data/raw/master/en_vi_iwslt.tar.gz
!mkdir data_bin
!tar -xvf  'en_vi_iwslt.tar.gz' -C 'data_bin'

--2021-03-11 12:26:34--  https://github.com/hoangtrungchinh/clc_data/raw/master/en_vi_iwslt.tar.gz
Resolving github.com (github.com)... 52.74.223.119
Connecting to github.com (github.com)|52.74.223.119|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/hoangtrungchinh/clc_data/master/en_vi_iwslt.tar.gz [following]
--2021-03-11 12:26:35--  https://raw.githubusercontent.com/hoangtrungchinh/clc_data/master/en_vi_iwslt.tar.gz
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.111.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 9044100 (8,6M) [application/octet-stream]
Saving to: ‘en_vi_iwslt.tar.gz’

en_vi_iwslt.tar.gz  100%[===================>]   8,62M  2,66MB/s    in 3,3s    

2021-03-11 12:26:38 (2,60 MB/s) - ‘en_vi_iwslt.tar.gz’ saved [9044100/904410

In [4]:
# import file
import numpy as np
import glob

en_files = sorted(glob.glob("data_bin/*.en"))
vi_files = sorted(glob.glob("data_bin/*.vi"))
print(en_files)
print(vi_files)

lst_en = []
lst_vi = []

start = time.time()

for file in en_files:
  with open(file) as file_in:
    for line in file_in:
      lst_en.append(line)

for file in vi_files:
  with open(file) as file_in:
    for line in file_in:
      lst_vi.append(line)

print(len(lst_en))
print(len(lst_vi))

['data_bin/IWSLT15.TED.tst2012.en-vi.en', 'data_bin/IWSLT15.TED.tst2013.en-vi.en', 'data_bin/IWSLT15.TED.tst2015.en-vi.en', 'data_bin/train.en']
['data_bin/IWSLT15.TED.tst2012.en-vi.vi', 'data_bin/IWSLT15.TED.tst2013.en-vi.vi', 'data_bin/IWSLT15.TED.tst2015.en-vi.vi', 'data_bin/train.vi']
120956
120956


In [5]:
# SPLIT TRAIN, TEST, VALID
from sklearn.model_selection import train_test_split
en_train, en_test_valid, vi_train, vi_test_valid =  train_test_split(lst_en, lst_vi, test_size=0.01240120374, random_state=123)
en_valid, en_test, vi_valid, vi_test = train_test_split(en_test_valid, vi_test_valid, test_size=0.666666666, random_state=123)
print(len(en_train))
print(len(vi_train))
print(len(en_valid))
print(len(vi_valid))
print(len(en_test))
print(len(vi_test))
print(en_train[20])
print(vi_train[20])
print(en_valid[-1])
print(vi_valid[-1])
print(en_test[-1])
print(vi_test[-1])

119456
119456
500
500
1000
1000
And what I would like to maybe invite you to do by the end of this talk is explore where you are today , for two reasons . One : so that you can contribute more . And two : so that hopefully we can not just understand other people more , but maybe appreciate them more , and create the kinds of connections that can stop some of the challenges that we face in our society today .

Và tôi mong muốn là mời bạn tham gia một việc trước khi kết thúc buổi trò chuyện này , là khám phá ra bạn đang ở đâu ngày hôm nay , vì hai lý do . Một : bạn có thể cống hiến nhiều hơn . Và hai : hy vọng ta có thể không chỉ hiểu người khác nhiều hơn , mà có lẽ còn thấy biết ơn họ hơn , và tạo ra những mối liên kết có thể chặn trước vài vấn đề mà chúng ta đối mặt trong xã hội ngày nay .

So we have to wonder , if there is a multiverse , in some other patch of that multiverse , are there creatures ?

Thế nên ta phải tự hỏi , nếu có nhiều vũ trụ , và trong một vài phần của những ngân 

In [6]:
file_variable = [en_train,vi_train,en_valid,vi_valid,en_test,vi_test]
file_names = ["en_train","vi_train","en_valid","vi_valid","en_test","vi_test"]

for i in range(len(file_names)):
  with open(file_names[i], 'w') as f:
    for item in file_variable[i]:
      f.write(item)
!ls -al

total 36836
drwxrwxr-x 3 chinh chinh     4096 Thg 3  11 12:26 .
drwxrwxr-x 7 chinh chinh     4096 Thg 3  11 12:26 ..
drwxrwxr-x 2 chinh chinh     4096 Thg 3  11 12:26 data_bin
-rw-rw-r-- 1 chinh chinh   104840 Thg 3  11 12:26 en_test
-rw-rw-r-- 1 chinh chinh 12363629 Thg 3  11 12:26 en_train
-rw-rw-r-- 1 chinh chinh    52563 Thg 3  11 12:26 en_valid
-rw-rw-r-- 1 chinh chinh  9044100 Thg 3  11 12:26 en_vi_iwslt.tar.gz
-rw-rw-r-- 1 chinh chinh   135053 Thg 3  11 12:26 vi_test
-rw-rw-r-- 1 chinh chinh 15927506 Thg 3  11 12:26 vi_train
-rw-rw-r-- 1 chinh chinh    68047 Thg 3  11 12:26 vi_valid


In [7]:
from sentence_transformers import SentenceTransformer, util
model = SentenceTransformer('stsb-bert-large')
# # model = SentenceTransformer('LaBSE')
# #Sentences are encoded by calling model.encode()
# emb1 = model.encode("This is a red cat with a hat.")
# emb2 = model.encode("Have you seen my red cat?")

# cos_sim = util.pytorch_cos_sim(emb1, emb2)
# print("Cosine-Similarity:", cos_sim)

In [8]:
# print(cos_sim.numpy()[0][0])

In [9]:
start = time.time()
srcfile = "en_train"
tarfile = "vi_train"
# lst_srcfile = open(srcfile, "r").readlines()
# lst_tarfile = open(tarfile, "r").readlines()
lst_srcfile = en_train
lst_tarfile = vi_train

vec_lst_srcfile = model.encode(lst_srcfile)
print('=== Ending, Total time (second): ', time.time() - start)

=== Ending, Total time (second):  1345.5654425621033


Test Cosin similarity

In [10]:
import faiss
# print(vec_lst_srcfile.shape[1])
start = time.time()
index = faiss.IndexFlatL2(vec_lst_srcfile.shape[1])
index.ntotal
faiss.normalize_L2(vec_lst_srcfile)
index.add(vec_lst_srcfile)
k = 6
distance, index = index.search(vec_lst_srcfile, k)

print('=== Ending, Total time (second): ', time.time() - start)
print(len(distance))
print(len(index))

print(index)
print(distance)

=== Ending, Total time (second):  73.82606601715088
119456
119456
[[     0  69286  10275  54878  18040  77506]
 [     1  64134  56895  73664 110494  17316]
 [     2  64614  28383  65877   8052 115420]
 ...
 [119453  19843  37568  64536  16431  95416]
 [119454  99954  71775  10270 117634  53761]
 [119455  87353  71958  14703  23335  88050]]
[[2.3841858e-07 8.4685552e-01 8.8518691e-01 8.9557350e-01 9.4082844e-01
  9.5213497e-01]
 [4.7683716e-07 3.8534057e-01 4.3862689e-01 4.4487023e-01 4.6250558e-01
  4.7786093e-01]
 [2.3841858e-07 8.4031105e-01 9.1200197e-01 9.3302917e-01 9.4673765e-01
  9.4906569e-01]
 ...
 [0.0000000e+00 6.8923903e-01 8.1287575e-01 8.6379361e-01 8.8436067e-01
  9.1680312e-01]
 [4.7683716e-07 7.5868452e-01 8.3096647e-01 8.9616454e-01 9.0191150e-01
  9.0270007e-01]
 [2.3841858e-07 5.8190024e-01 6.0680532e-01 6.5269065e-01 6.5279567e-01
  6.8669903e-01]]


In [11]:
i = 6
j = k-1
print(index[i][j])
print("==================================")
print(distance[i][j])
a = vec_lst_srcfile[i]
# print(a)
b = vec_lst_srcfile[index[i][j]]
# TEST
dist_squared = np.sum(np.square(a - b))
print(dist_squared)

82931
0.71878266
0.71878254


In [12]:
start = time.time()
saperate = " || "

src_label = "S"
emb_label = "E"
thres_arr = [0.9, 0.8, 0.7, 0.6]
for i in range(len(thres_arr)):
    threshold = thres_arr[i]
    out_file_write = open("en_train_EM_"+str(thres_arr[i]), 'w')
    out_file_write_score = open("en_train_EM_score_"+str(thres_arr[i]), 'w')
    out_file_write_factor = open("en_train_EM_factor_"+str(thres_arr[i]), 'w')
    num_gth_thres = 0

    for i in range(len(lst_srcfile)):
        score = distance[i][1]
        content = ""
        content_label_arr = []
        if score >= threshold:
            num_gth_thres += 1
            best_simi_index = index[i][1]
            content = lst_srcfile[i].strip() + saperate + lst_tarfile[best_simi_index].strip()

            content_label = [src_label] * len(lst_srcfile[i].split())
            content_label.append(emb_label)
            content_label = content_label + [emb_label] * len(lst_tarfile[best_simi_index].split())

            content_label_arr = " ".join(content_label)
        else:
            content = lst_srcfile[i].strip()
            content_label = [src_label] * len(lst_srcfile[i].split())
            content_label_arr = " ".join(content_label)
 
        out_file_write.writelines(content+ "\n")    
        out_file_write_factor.writelines(content_label_arr + "\n")
        out_file_write_score.writelines(str(score) + "\n")

    print('threshold =', threshold, "EM sentences =", num_gth_thres, "/", len(lst_srcfile), num_gth_thres/len(lst_srcfile), "%" )

    out_file_write.close()
    out_file_write_score.close()
    out_file_write_factor.close()

done = time.time()
elapsed = done - start
print('=== Ending, Total time (second): ', elapsed)

threshold = 0.9 EM sentences = 7035 / 119456 0.05889197696222877 %
threshold = 0.8 EM sentences = 22259 / 119456 0.1863363916421109 %
threshold = 0.7 EM sentences = 46345 / 119456 0.3879671175997857 %
threshold = 0.6 EM sentences = 71735 / 119456 0.6005139967854273 %
=== Ending, Total time (second):  11.925443410873413
