INSTALL
- FAISS - 
- Sent2Vec

In [1]:
import numpy as np
import faiss   

In [2]:
import os
import time
name = "Faiss-EM-LAW-bert-en-vi-0.999-"+ str(time.strftime("%Y%m%d-%H%M"))

!mkdir $name
path = os.getcwd() + "/" + name
os.chdir(path)

!pwd


os.chdir(path)


# import os
# os.chdir("/home/lw/clc_fairseq/TED-20210121-1335")

/home/chinh/clc_data/Script/Faiss-EM-LAW-bert-en-vi-0.999-20210408-1810


In [3]:
!wget https://github.com/hoangtrungchinh/clc_data/raw/master/law.tar.gz
!mkdir data_bin
!tar -xvf  'law.tar.gz' -C 'data_bin'

--2021-04-08 18:10:36--  https://github.com/hoangtrungchinh/clc_data/raw/master/law.tar.gz
Resolving github.com (github.com)... 192.30.255.113
Connecting to github.com (github.com)|192.30.255.113|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/hoangtrungchinh/clc_data/master/law.tar.gz [following]
--2021-04-08 18:10:37--  https://raw.githubusercontent.com/hoangtrungchinh/clc_data/master/law.tar.gz
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.108.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 988814 (966K) [application/octet-stream]
Saving to: ‘law.tar.gz’

law.tar.gz          100%[===================>] 965,64K  2,97MB/s    in 0,3s    

2021-04-08 18:10:38 (2,97 MB/s) - ‘law.tar.gz’ saved [988814/988814]

_law.vi
_law.en


In [4]:
# import file
import numpy as np
import glob

en_files = sorted(glob.glob("data_bin/*.en"))
vi_files = sorted(glob.glob("data_bin/*.vi"))
print(en_files)
print(vi_files)

lst_en = []
lst_vi = []

start = time.time()

for file in en_files:
  with open(file) as file_in:
    for line in file_in:
      lst_en.append(line)

for file in vi_files:
  with open(file) as file_in:
    for line in file_in:
      lst_vi.append(line)

print(len(lst_en))
print(len(lst_vi))

['data_bin/_law.en']
['data_bin/_law.vi']
17967
17967


In [5]:
# SPLIT TRAIN, TEST, VALID
from sklearn.model_selection import train_test_split
en_train, en_test_valid, vi_train, vi_test_valid =  train_test_split(lst_en, lst_vi, test_size=0.2, random_state=123)
en_valid, en_test, vi_valid, vi_test = train_test_split(en_test_valid, vi_test_valid, test_size=0.5, random_state=123)
print(len(en_train))
print(len(vi_train))
print(len(en_valid))
print(len(vi_valid))
print(len(en_test))
print(len(vi_test))
print(en_train[20])
print(vi_train[20])
print(en_valid[-1])
print(vi_valid[-1])
print(en_test[-1])
print(vi_test[-1])

14373
14373
1797
1797
1797
1797
A person aged from fifteen years to below eighteen years may be an authorized representative, except where the law provides for that the civil transaction must be entered into and performed by a person who has reached eighteen years of age.

Người từ đủ mười lăm tuổi đến chưa đủ mười tám tuổi có thể là người đại diện theo uỷ quyền, trừ trường hợp pháp luật quy định giao dịch dân sự phải do người từ đủ mười tám tuổi trở lên xác lập, thực hiện.

The Law on Bankruptcy is applied to the bankruptcy process of every enterprise and cooperative based in the territory of Vietnam.

Luật Phá sản được áp dụng khi giải quyết phá sản đối với doanh nghiệp, hợp tác xã được thành lập trên lãnh thổ Cộng hòa xã hội chủ nghĩa Việt Nam.

A lawsuit is instituted over an administrative decision or act of a provincial-level People’s Committee or provincial-level People’s Committee chairperson which is related to many subjects;

Khiếu kiện quyết định hành chính, hành vi hành chí

In [6]:
file_variable = [en_train,vi_train,en_valid,vi_valid,en_test,vi_test]
file_names = ["en_train","vi_train","en_valid","vi_valid","en_test","vi_test"]

for i in range(len(file_names)):
  with open(file_names[i], 'w') as f:
    for item in file_variable[i]:
      f.write(item)
!ls -al

total 6672
drwxrwxr-x  3 chinh chinh    4096 Thg 4   8 18:10 .
drwxrwxr-x 16 chinh chinh    4096 Thg 4   8 18:10 ..
drwxrwxr-x  2 chinh chinh    4096 Thg 4   8 18:10 data_bin
-rw-rw-r--  1 chinh chinh  257314 Thg 4   8 18:10 en_test
-rw-rw-r--  1 chinh chinh 2096540 Thg 4   8 18:10 en_train
-rw-rw-r--  1 chinh chinh  265528 Thg 4   8 18:10 en_valid
-rw-rw-r--  1 chinh chinh  988814 Thg 4   8 18:10 law.tar.gz
-rw-rw-r--  1 chinh chinh  314903 Thg 4   8 18:10 vi_test
-rw-rw-r--  1 chinh chinh 2560025 Thg 4   8 18:10 vi_train
-rw-rw-r--  1 chinh chinh  325494 Thg 4   8 18:10 vi_valid


In [7]:
from sentence_transformers import SentenceTransformer, util
model = SentenceTransformer('stsb-bert-large')
# # model = SentenceTransformer('LaBSE')
# #Sentences are encoded by calling model.encode()
# emb1 = model.encode("This is a red cat with a hat.")
# emb2 = model.encode("Have you seen my red cat?")

# cos_sim = util.pytorch_cos_sim(emb1, emb2)
# print("Cosine-Similarity:", cos_sim)

In [8]:
# print(cos_sim.numpy()[0][0])

In [9]:
start = time.time()
srcfile = "en_train"
tarfile = "vi_train"
# lst_srcfile = open(srcfile, "r").readlines()
# lst_tarfile = open(tarfile, "r").readlines()
lst_srcfile = en_train
lst_tarfile = vi_train

vec_lst_srcfile = model.encode(lst_srcfile)
print('=== Ending, Total time (second): ', time.time() - start)

=== Ending, Total time (second):  173.6101269721985


Test Cosin similarity

In [10]:
import faiss
# print(vec_lst_srcfile.shape[1])
start = time.time()
index = faiss.IndexFlatL2(vec_lst_srcfile.shape[1])
index.ntotal
faiss.normalize_L2(vec_lst_srcfile)
index.add(vec_lst_srcfile)
k = 6
distance, index = index.search(vec_lst_srcfile, k)

print('=== Ending, Total time (second): ', time.time() - start)
print(len(distance))
print(len(index))

print(index)
print(distance)

=== Ending, Total time (second):  1.0145559310913086
14373
14373
[[    0  4092  3389  4120  8037  3532]
 [    1  1610  9343 11153  6364  7317]
 [    2  4401  4307  1745  4738 11962]
 ...
 [14370  4992  6763  5200  6329 11081]
 [14371  5816 13903  8185 13816 10946]
 [14372  8951  1254  1865  1823  4448]]
[[0.0000000e+00 2.2767282e-01 2.3257637e-01 2.3575115e-01 3.0760300e-01
  3.1662929e-01]
 [0.0000000e+00 4.1190624e-01 5.8814275e-01 6.2055159e-01 6.2616181e-01
  6.2906194e-01]
 [2.3841858e-07 1.7081940e-01 3.8323689e-01 5.3106880e-01 5.8402133e-01
  6.3239777e-01]
 ...
 [4.7683716e-07 3.9565945e-01 4.4730735e-01 4.6415091e-01 4.8132908e-01
  5.1066887e-01]
 [1.1920929e-07 2.5233459e-01 2.9826128e-01 3.1739175e-01 3.7581074e-01
  4.2220151e-01]
 [0.0000000e+00 1.9465077e-01 4.9963856e-01 5.0489318e-01 5.5149758e-01
  5.8095956e-01]]


In [11]:
i = 6
j = k-1
print(index[i][j])
print("==================================")
print(distance[i][j])
a = vec_lst_srcfile[i]
# print(a)
b = vec_lst_srcfile[index[i][j]]
# TEST
dist_squared = np.sum(np.square(a - b))
print(dist_squared)

7014
0.523283
0.5232831


In [12]:
start = time.time()
saperate = " || "

src_label = "S"
emb_label = "E"
thres_arr = [0.8, 0.85, 0.9, 0.95, 0.99]
for i in range(len(thres_arr)):
    threshold = thres_arr[i]
    out_file_write = open("en_train_EM_"+str(thres_arr[i]), 'w')
    out_file_write_score = open("en_train_EM_score_"+str(thres_arr[i]), 'w')
    out_file_write_factor = open("en_train_EM_factor_"+str(thres_arr[i]), 'w')
    num_gth_thres = 0

    for i in range(len(lst_srcfile)):
        score = distance[i][1]
        content = ""
        content_label_arr = []
        if score >= threshold:
            num_gth_thres += 1
            best_simi_index = index[i][1]
            content = lst_srcfile[i].strip() + saperate + lst_tarfile[best_simi_index].strip()

            content_label = [src_label] * len(lst_srcfile[i].split())
            content_label.append(emb_label)
            content_label = content_label + [emb_label] * len(lst_tarfile[best_simi_index].split())

            content_label_arr = " ".join(content_label)
        else:
            content = lst_srcfile[i].strip()
            content_label = [src_label] * len(lst_srcfile[i].split())
            content_label_arr = " ".join(content_label)
 
        out_file_write.writelines(content+ "\n")    
        out_file_write_factor.writelines(content_label_arr + "\n")
        out_file_write_score.writelines(str(score) + "\n")

    print('threshold =', threshold, "EM sentences =", num_gth_thres, "/", len(lst_srcfile), num_gth_thres/len(lst_srcfile), "%" )

    out_file_write.close()
    out_file_write_score.close()
    out_file_write_factor.close()

done = time.time()
elapsed = done - start
print('=== Ending, Total time (second): ', elapsed)

threshold = 0.8 EM sentences = 177 / 14373 0.012314756835733668 %
threshold = 0.85 EM sentences = 90 / 14373 0.006261740763932373 %
threshold = 0.9 EM sentences = 44 / 14373 0.0030612954845891604 %
threshold = 0.95 EM sentences = 20 / 14373 0.0013914979475405274 %
threshold = 0.99 EM sentences = 10 / 14373 0.0006957489737702637 %
=== Ending, Total time (second):  1.2004516124725342
