INSTALL
- FAISS - 
- Sent2Vec

In [1]:
import numpy as np
import faiss   

In [2]:
import os
import time
name = "Faiss-EM-OPUS-bert-vi-en"+ str(time.strftime("%Y%m%d-%H%M"))

!mkdir $name
path = os.getcwd() + "/" + name
os.chdir(path)

!pwd
os.chdir(path)

/home/chinh/clc_data/Script/Faiss-EM-OPUS-bert-vi-en20210304-2211


In [3]:
!wget https://github.com/hoangtrungchinh/clc_data/raw/master/opus-100-corpus.zip
!mkdir data_bin
!unzip 'opus-100-corpus.zip' -d 'data_bin'

--2021-03-04 22:11:28--  https://github.com/hoangtrungchinh/clc_data/raw/master/opus-100-corpus.zip
Resolving github.com (github.com)... 52.74.223.119
Connecting to github.com (github.com)|52.74.223.119|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/hoangtrungchinh/clc_data/master/opus-100-corpus.zip [following]
--2021-03-04 22:11:29--  https://raw.githubusercontent.com/hoangtrungchinh/clc_data/master/opus-100-corpus.zip
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.108.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 30690851 (29M) [application/zip]
Saving to: ‘opus-100-corpus.zip’

opus-100-corpus.zip 100%[===================>]  29,27M  1,85MB/s    in 23s     

2021-03-04 22:11:54 (1,25 MB/s) - ‘opus-100-corpus.zip’ saved [30690851/30690851]

In [4]:
# import file
import numpy as np
import glob

en_files = sorted(glob.glob("data_bin/*.en"))
vi_files = sorted(glob.glob("data_bin/*.vi"))
print(en_files)
print(vi_files)

lst_en = []
lst_vi = []

start = time.time()

for file in en_files:
  with open(file) as file_in:
    for line in file_in:
      lst_en.append(line.strip())

for file in vi_files:
  with open(file) as file_in:
    for line in file_in:
      lst_vi.append(line.strip())

print(len(lst_en))
print(len(lst_vi))

['data_bin/opus.en-vi-dev.en', 'data_bin/opus.en-vi-test.en', 'data_bin/opus.en-vi-train.en']
['data_bin/opus.en-vi-dev.vi', 'data_bin/opus.en-vi-test.vi', 'data_bin/opus.en-vi-train.vi']
1004000
1004000


In [5]:
# SPLIT TRAIN, TEST, VALID
from sklearn.model_selection import train_test_split
en_train, en_test_valid, vi_train, vi_test_valid =  train_test_split(lst_en, lst_vi, test_size=0.2, random_state=123)
en_valid, en_test, vi_valid, vi_test = train_test_split(en_test_valid, vi_test_valid, test_size=0.5, random_state=123)
print(len(en_train))
print(len(vi_train))
print(len(en_valid))
print(len(vi_valid))
print(len(en_test))
print(len(vi_test))
print(en_train[20])
print(vi_train[20])
print(en_valid[-1])
print(vi_valid[-1])
print(en_test[-1])
print(vi_test[-1])

803200
803200
100400
100400
100400
100400
Childs?
Childs?
It's powered up now, isn't it?
Bây giờ nó bật rồi phải không nhỉ?
Why the hell are you going to Cuddy's baby naming?
Bị làm sao mà anh lại đi dự lễ đặt tên em bé của Cuddy chứ?


In [6]:
file_variable = [en_train,vi_train,en_valid,vi_valid,en_test,vi_test]
file_names = ["en_train","vi_train","en_valid","vi_valid","en_test","vi_test"]

for i in range(len(file_names)):
  with open(file_names[i], 'w') as f:
    for item in file_variable[i]:
      f.write(item)
      f.write("\n")
    
!ls -al

total 105172
drwxrwxr-x 3 chinh chinh     4096 Thg 3   4 22:11 .
drwxrwxr-x 7 chinh chinh     4096 Thg 3   4 22:11 ..
drwxrwxr-x 2 chinh chinh     4096 Thg 3   4 22:11 data_bin
-rw-rw-r-- 1 chinh chinh  3318349 Thg 3   4 22:11 en_test
-rw-rw-r-- 1 chinh chinh 26563375 Thg 3   4 22:11 en_train
-rw-rw-r-- 1 chinh chinh  3328557 Thg 3   4 22:11 en_valid
-rw-rw-r-- 1 chinh chinh 30690851 Thg 3   4 22:11 opus-100-corpus.zip
-rw-rw-r-- 1 chinh chinh  4365722 Thg 3   4 22:11 vi_test
-rw-rw-r-- 1 chinh chinh 35019161 Thg 3   4 22:11 vi_train
-rw-rw-r-- 1 chinh chinh  4382771 Thg 3   4 22:11 vi_valid


In [7]:
from sentence_transformers import SentenceTransformer, util
model = SentenceTransformer('stsb-bert-large')
# # model = SentenceTransformer('LaBSE')
# #Sentences are encoded by calling model.encode()
# emb1 = model.encode("This is a red cat with a hat.")
# emb2 = model.encode("Have you seen my red cat?")

# cos_sim = util.pytorch_cos_sim(emb1, emb2)
# print("Cosine-Similarity:", cos_sim)

In [8]:
# print(cos_sim.numpy()[0][0])

In [9]:
start = time.time()
srcfile = "vi_train"
tarfile = "en_train"
lst_srcfile = vi_train
lst_tarfile = en_train

vec_lst_srcfile = model.encode(lst_srcfile)
print('=== Ending, Total time (second): ', time.time() - start)

=== Ending, Total time (second):  5533.622172355652


Test Cosin similarity

In [10]:
import faiss
# print(vec_lst_srcfile.shape[1])
start = time.time()
index = faiss.IndexFlatL2(vec_lst_srcfile.shape[1])
index.ntotal
faiss.normalize_L2(vec_lst_srcfile)
index.add(vec_lst_srcfile)
k = 6
distance, index = index.search(vec_lst_srcfile, k)

print('=== Ending, Total time (second): ', time.time() - start)
print(len(distance))
print(len(index))

print(index)
print(distance)

=== Ending, Total time (second):  4194.028205394745
803200
803200
[[     0 746661 164755 102212 320461 362756]
 [     1 474683 442306 147156 323581  79135]
 [     2 185749 279517 374097 238361 118951]
 ...
 [803197 229860 211180 174635 324031 119032]
 [803198  99432  89647 768526 620014 190710]
 [112858 803199 387796 404804 265249 119586]]
[[4.7683716e-07 6.1151981e-03 3.9579630e-02 4.1592479e-02 4.2745113e-02
  4.3224692e-02]
 [0.0000000e+00 5.2904963e-02 5.7109237e-02 5.7109475e-02 5.8486104e-02
  5.8486223e-02]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  0.0000000e+00]
 ...
 [0.0000000e+00 2.2019863e-02 3.1281948e-02 3.1281948e-02 3.1281948e-02
  3.1281948e-02]
 [0.0000000e+00 1.7808914e-02 1.9705892e-02 2.0296335e-02 2.2725224e-02
  2.7722716e-02]
 [0.0000000e+00 0.0000000e+00 1.1308074e-01 1.2793410e-01 1.5686762e-01
  1.5776348e-01]]


In [11]:
j = k-1
# TEST
for i in range(10):
    a = vec_lst_srcfile[i]
    b = vec_lst_srcfile[index[i][j]]
    dist_squared = np.sum(np.square(a - b))
    print("index:",index[i][j], "distance:",distance[i][j], "tested:",dist_squared)

index: 362756 distance: 0.043224692 tested: 0.043224446
index: 79135 distance: 0.058486223 tested: 0.05848638
index: 118951 distance: 0.0 tested: 0.0
index: 29136 distance: 0.0 tested: 0.0
index: 429624 distance: 0.06252098 tested: 0.062521
index: 274120 distance: 0.14807916 tested: 0.1480794
index: 288843 distance: 0.34693933 tested: 0.3469394
index: 130918 distance: 0.062124252 tested: 0.062124353
index: 198135 distance: 0.046062827 tested: 0.0460632
index: 357182 distance: 0.10263455 tested: 0.10263466


In [12]:
start = time.time()
saperate = " || "

src_label = "S"
emb_label = "E"
thres_arr = [0.9, 0.8, 0.7, 0.6]
for i in range(len(thres_arr)):
    threshold = thres_arr[i]
    out_file_write = open("vi_train_EM_"+str(thres_arr[i]), 'w')
    out_file_write_score = open("vi_train_EM_score_"+str(thres_arr[i]), 'w')
    out_file_write_factor = open("vi_train_EM_factor_"+str(thres_arr[i]), 'w')
    num_gth_thres = 0

    for i in range(len(lst_srcfile)):
        score = distance[i][1]
        content = ""
        content_label_arr = []
        if score >= threshold:
            num_gth_thres += 1
            best_simi_index = index[i][1]
            content = lst_srcfile[i] + saperate + lst_tarfile[best_simi_index]

            content_label = [src_label] * len(lst_srcfile[i].split())
            content_label.append(emb_label)
            content_label = content_label + [emb_label] * len(lst_tarfile[best_simi_index].split())

            content_label_arr = " ".join(content_label)
        else:
            content = lst_srcfile[i]
            content_label = [src_label] * len(lst_srcfile[i].split())
            content_label_arr = " ".join(content_label)

        out_file_write.writelines(content+ "\n")    
        out_file_write_factor.writelines(content_label_arr + "\n")
        out_file_write_score.writelines(str(score) + "\n")

    print('threshold =', threshold, "EM sentences =", num_gth_thres, "/", len(lst_srcfile), num_gth_thres/len(lst_srcfile), "%" )

    out_file_write.close()
    out_file_write_score.close()
    out_file_write_factor.close()

done = time.time()
elapsed = done - start
print('=== Ending, Total time (second): ', elapsed)

threshold = 0.9 EM sentences = 1125 / 803200 0.0014006474103585658 %
threshold = 0.8 EM sentences = 2447 / 803200 0.0030465637450199203 %
threshold = 0.7 EM sentences = 4604 / 803200 0.00573207171314741 %
threshold = 0.6 EM sentences = 8245 / 803200 0.010265189243027889 %
=== Ending, Total time (second):  27.676761627197266
